# Generated by Django 5.0.3 on 2024-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('word', models.CharField(default='testn/a', max_length=50, primary_key=True, serialize=False)),
                ('definiton', models.CharField(max_length=1000)),
                ('example', models.CharField(max_length=255)),
            ],
        ),
    ]
