# Generated by Django 5.0.3 on 2024-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('word', models.ManyToManyField(to='vocabulary.words')),
            ],
        ),
    ]
