# Generated by Django 5.0.3 on 2024-03-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='word_type',
            field=models.CharField(choices=[('noun', 'noun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb')], default='noun', max_length=9),
        ),
    ]
