# Generated by Django 5.0.3 on 2024-03-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_words_word_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='definiton',
            new_name='definition',
        ),
    ]
